### ISSUE TITLE
Make multilingual properties display current locale

### ISSUE THREAD

**Issue by loftux** [loftuxab/alfresco-community-loftux#5]
The mltext properties cause all sorts of confusion when users with different locale edits them. This is a workaround to at least display the locale the ml property is saved with.
https://issues.alfresco.com/jira/browse/ALF-11198

**Comment by MarcelloModica** [comment]
Based on request here https://issues.alfresco.com/jira/browse/ALF-11166
May i know if you have added a form to change labels in differets locale?
